### ISSUE TITLE
Consider updating the ddev configuration command

### ISSUE THREAD

**Issue by rpkoller** [TravisCarden/ddev-drupal-xb-dev#39]
i've just noticed a minor detail looking at the readme. at the moment the instructions for the configuration command in the readme are: 

```
ddev config --project-type=drupal --php-version=8.3 --docroot=web
```

"Problem" with the release of ddev 1.24.0 https://github.com/ddev/ddev/releases/tag/v1.24.0 the `drupal11` project type was added and `drupal` became the alias for it (drupal is the alias for the latest major version of drupal). the project is using recommended-project:10.x@dev, so that means the version of drupal is version 10, while by choosing the project type drupal you are setting the project to drupal 11. strictly speaking, if you compare the resulting settings, it is not much of a difference:

drupal 10: 

```
name: d10er
type: drupal10
docroot: web
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
corepack_enable: false
```

drupal 11 and drupal : 
```
name: d11er
type: drupal11
docroot: web
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
corepack_enable: true
```

so the only difference is that you are having corepack enable set to true which is introduced in drupal 11 https://www.drupal.org/node/3428571 - in drupal 10 yarn 4 is unavailable. and setting the php version to 8.3 is unnecessary since 8.3 is the default for drupal10/drupal11/drupal project types.... but it would be probably more accurate nevertheless to change the ddev config line to: 

```
ddev config --project-type=drupal10 --docroot=web
```
